POST https://localhost:7055/authenticate
Accept: application/json
Content-Type: application/json

{
    "username": "admin",
    "password": "admin@123"
}

> {%
    client.global.set("token", response.body.json.token);
%}
