POST https://localhost:7055/weatherforecast
Accept: application/json
Content-Type: application/json
Authorization: bearer {{token}}

{
    "date": "2022-08-28T00:00:00",
    "temperatureCelsius": 15,
    "summary": "Creating Test"
}
