PUT https://localhost:7055/weatherforecast/43903282-c4b3-42f9-99cc-fd234ee6941d
Accept: application/json
Content-Type: application/json
Authorization: bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6WyI2Y2M0MDY1OTc3ZGQ0MjFiYjVjNDNmZGY5N2Q5NGRlNiIsImE4YTNlNzQ5NTQ3YzQwNTQ4ODIxMDY4OWNiMzg5NGI3Il0sImp0aSI6ImE4YTNlNzQ5NTQ3YzQwNTQ4ODIxMDY4OWNiMzg5NGI3IiwibmJmIjoxNjYyNDk5OTU3LCJleHAiOjE2NjI1NTk5NTcsImlhdCI6MTY2MjQ5OTk1NywiaXNzIjoiQXBpSXNzdWVyIiwiYXVkIjoiQXBpQXVkaWVuY2UifQ.pT4LAfXQZ4WwVlAvZnqAX6YU48_bR6GFaLd5KMnYoJIHowcROxwJVBQIrLxbEfoMP7Vg6ZpttJ3H5RD93Rd-S9QUGbZJHQHycN_w3T50gnln3LVfuXDtV8ebR_uf90oAoFt9iwReimLCTUJ16c8tr1DU6yRxeNOyj7Q7AHjQaG8_jmUcHAH_QcVo6-zt6DE4z67b3O_mt5MKVuWbOD0DlunfpE44ZqgxiuBX9YRPm-K_okKjDgBbpSk0ibK5oReTj96QQRjpxwj7KChQjpisj-VnO64eqmgJS21mYOnDGnxL7ZwNGkmHqUBwM2gqSNXGJEIRIvQ5RIXMScuqiDO66g

{
    "id": "43903282-c4b3-42f9-99cc-fd234ee6941d",
    "date": "2022-08-28T00:00:00",
    "temperatureCelsius": 15,
    "summary": "UPDATE TEST"
}
