PUT https://localhost:7055/weatherforecast/43903282-c4b3-42f9-99cc-fd234ee6941d
Accept: application/json
Content-Type: application/json
Authorization: bearer {{token}}

{
    "id": "43903282-c4b3-42f9-99cc-fd234ee6941d",
    "date": "2022-08-28T00:00:00",
    "temperatureCelsius": 15,
    "summary": "UPDATE TEST"
}
