name: SonarQube Code Analysis and Coverage
on:
    push:
        branches: [ master ]
jobs:
    sonarqube:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2
            -   name: Install .NET Core
                run: dotnet tool install -g dotnet-sonarqube
            -   name: Run SonarQube analysis
                env:
                    SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
                    SONARQUBE_ORG: ${{ secrets.SONARQUBE_ORG }}
                    SONARQUBE_PROJECT: ${{ secrets.SONARQUBE_PROJECT }}
                run: dotnet sonarqube analyze --coverage --assembly-name FastEndpointTemplate
